version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trv_sanbox_ui
    ports:
      - "3020:80"
    env_file:
      - .env
    restart: always
