version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sandbox_tracer_frontend
    ports:
      - "3000:80"
    env_file:
      - .env
    restart: always
